# -*- coding: utf-8 -*-
"""ade_shield

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDiq4bzMR1j31i5GjeXfEhnvbT22Eb56
"""

import streamlit as st
import pandas as pd
import altair as alt

# 1. Page Configuration (Wide Layout for Split Screen)
st.set_page_config(page_title="ADE Shield - Pharmacist View", layout="wide")

# 2. Title and Header
st.title("🛡️ ADE Shield: Pharmacist Intervention Console")
st.markdown("---")

# 3. Create the Split Layout (30% Left, 70% Right)
col_left, col_right = st.columns([3, 7])

# --- LEFT COLUMN: THE "INBOX" ---
with col_left:
    st.subheader("⚠️ Patient Queue")

    # Simulating a "Selected" Patient Card with a success/error box
    st.error("**John Smith** (Room 302)\n\n🔴 **Risk: 94% (CRITICAL)**\n\n*Issue: Warfarin Interaction*")

    # Other Patients (Simulated as buttons or text)
    st.warning("**Maria Garcia** (Room 410)\n\n🟠 **Risk: 78% (HIGH)**\n\n*Issue: AKI / Creatinine*")
    st.info("**David Lee** (Room 105)\n\n🟢 **Risk: 12% (LOW)**\n\n*Issue: Stable / Monitoring*")

# --- RIGHT COLUMN: THE "DEEP DIVE" ---
with col_right:
    # Header Zone
    st.subheader("Patient Analysis: John Smith (72M)")
    st.caption("Admit Dx: Atrial Fibrillation | Allergies: Penicillin")

    # The Big Score (Using Columns for alignment)
    metric_col1, metric_col2 = st.columns([2, 4])
    with metric_col1:
        st.metric(label="Predicted ADE Probability", value="94%", delta="CRITICAL")
    with metric_col2:
        st.markdown("#### 🚨 High Risk: Major Bleeding Event")
        st.markdown("Prediction window: Next 48 Hours")

    st.markdown("---")

    # The AI "Brain" (Feature Importance Chart)
    st.subheader("🔍 Why did the AI flag this?")
    st.caption("Top factors contributing to this risk score (XGBoost Feature Importance)")

    # Creating dummy data for the chart
    risk_data = pd.DataFrame({
        'Risk Factor': ['Drug Interaction (Warfarin + Amiodarone)', 'Lab: INR > 4.0', 'History: GI Bleed', 'Age > 70'],
        'Contribution': [45, 30, 15, 10]
    })

    # Horizontal Bar Chart
    chart = alt.Chart(risk_data).mark_bar(color='#ff4b4b').encode(
        x='Contribution',
        y=alt.Y('Risk Factor', sort='-x'),
        tooltip=['Risk Factor', 'Contribution']
    ).properties(height=200)

    st.altair_chart(chart, use_container_width=True)

    st.markdown("---")

    # The Clinical Evidence
    st.subheader("📋 Live Clinical Context")

    evidence_col1, evidence_col2 = st.columns(2)
    with evidence_col1:
        st.markdown("**Active Medications:**")
        st.markdown("- **Warfarin 5mg** (Oral) - *Active*")
        st.markdown("- **Amiodarone 200mg** (IV) - *Started 2 hrs ago*")

    with evidence_col2:
        st.markdown("**Relevant Labs (Last 4 hrs):**")
        st.markdown("- **INR:** 4.2 (High) 🔺")
        st.markdown("- **Hgb:** 11.2 (Stable)")

    st.markdown("---")

    # Action Buttons
    st.subheader("Recommended Action")
    st.info("💡 Recommendation: Hold Warfarin dose. Request repeat INR in 6 hours.")

    btn_col1, btn_col2, btn_col3 = st.columns([2, 2, 4])
    with btn_col1:
        st.button("✅ Approve Intervention", type="primary")
    with btn_col2:
        st.button("❌ Snooze Alert")